name: Test coverage

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install pytest
        pip install -r requirements.txt
    - name: Run tests with coverage
      run: |
        coverage run -m pytest
        coverage report --fail-under=80

  NotifyOnFailure:
    needs: build
    if: ${{ failure() }}
    uses: ./.github/workflows/feedback-slack-coverage.yml
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
