name: Dependency check

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

       - name: Run OWASP Dependency-Check
      run: |
        wget https://github.com/jeremylong/DependencyCheck/releases/download/v9.2.0/dependency-check-9.2.0-release.zip
        unzip dependency-check-9.2.0-release.zip
        mkdir -p dependency-reports
        ./dependency-check/bin/dependency-check.sh --project "FastAPI Backend" --scan . --out ./dependency-reports/dependency-check-report --apiKey ${{ secrets.NVD_API_KEY }}

    - name: Upload dependency-check report
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: ./dependency-reports/dependency-check-report
