name: Slack Notification on CI Pipeline Failure
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
  commit:
    branches: ["53-feedback-pipeline-naar-slack"]
  workflow_dispatch:

jobs:
  NotifyOnFailure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C07624WJDS4' # Update with your Slack channel ID
          slack-message: "CI Pipeline failed for ${{ github.repository }} ${{ github.ref_name }}\nPull Request: ${{ github.event.workflow_run.head_branch }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
