name: Slack Notification on CI Pipeline and Merge Failures

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
  push:
    branches: ["53-feedback-pipeline-naar-slack"]
  workflow_dispatch:

jobs:
  NotifyOnCIFailure:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack on CI Failure
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C07624WJDS4' # Update with your Slack channel ID
          slack-message: |
            :x: CI Pipeline failed for repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Workflow: ${{ github.event.workflow_run.name }}
            Commit: ${{ github.event.workflow_run.head_commit.message }}
            Author: ${{ github.event.workflow_run.head_commit.author.name }}
            Pull Request: ${{ github.event.workflow_run.head_branch }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        continue-on-error: true

  NotifyOnMergeFailure:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack on Merge Failure
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C07624WJDS4' # Update with your Slack channel ID
          slack-message: |
            :x: Merge conflict detected in repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Workflow: ${{ github.event.workflow_run.name }}
            Commit: ${{ github.event.workflow_run.head_commit.message }}
            Author: ${{ github.event.workflow_run.head_commit.author.name }}
            Pull Request: ${{ github.event.workflow_run.head_branch }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        continue-on-error: true
