name: Slack Notification on CI Pipeline Failure
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
  push:     # This is for testing in own branch 1
    branches: ["53-feedback-pipeline-naar-slack"]
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  NotifyOnFailure:
    if: ${{ always() }} #${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Debug GitHub context
        run: echo '${{ toJson(github) }}'

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C07624WJDS4' # Update with your Slack channel ID
          slack-message: |
            CI Pipeline failed for ${{ github.repository }} on branch ${{ github.ref_name }}
            Actor: ${{ github.event.pull_request.user.login }}
            Commit: <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
