name: Slack Notification on Coverage Pipeline Failure
on:
  workflow_call:
    secrets:
      SLACK_BOT_TOKEN:
        required: true
      SLACK_CHANNEL_ID:
        required: true
jobs:
  SendSlackNotificationOnFailure:
    runs-on: ubuntu-latest
    steps:
      - name: Haal de code uit de repository op
        uses: actions/checkout@v4

      - name: debug json output
        run: echo "${{ toJson(github) }}"

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: |
            :x: Coverage Pipeline failed for ${{ github.repository }} on branch ${{ github.ref_name }}
            Commit name: ${{ github.event.head_commit.message }} 
            Committer: ${{ github.event.head_commit.committer.name }}
            URL: ${{ github.event.head_commit.url }}
        env:
          # SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_BOT_TOKEN: 897dd843fd3eba2b94636f7e9666f864