name: Slack Notification on CI Pipeline Failure
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  NotifyOnFailure:
    runs-on: ubuntu-latest
    steps:
      - name: Debug GitHub context
        run: |
          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Workflow status: ${{ github.event.workflow_run.status }}"
          echo "Pull request number: ${{ github.event.workflow_run.pull_requests[0].number }}"
          echo "Actor: ${{ github.event.workflow_run.head_commit.author.name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Pull Request URL: ${{ github.event.workflow_run.pull_requests[0].html_url }}"

      - name: Send Slack notification
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C07624WJDS4' # Update with your Slack channel ID
          slack-message: |
            :x: CI Pipeline failed for ${{ github.repository }} on branch ${{ github.ref }}
            Actor: ${{ github.event.workflow_run.head_commit.author.name }}
            Pull-Request: <${{ github.event.workflow_run.pull_requests[0].html_url }}|${{ github.event.workflow_run.pull_requests[0].number }}>
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
