name: Slack Notification on Coverage Pipeline Failure
on:
  workflow_run:
    workflows: ["Test coverage"]
    types:
      - completed
jobs:
  SendSlackNotificationOnFailure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: |
            :x: CI Pipeline failed for ${{ github.event.workflow_run.repository.full_name }} on branch ${{ github.event.workflow_run.head_branch }}
            Actor: ${{ github.event.workflow_run.head_commit.author.name }}
            Commit: <${{ github.event.workflow_run.head_commit.url }}|${{ github.event.workflow_run.head_commit.message }}>
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}