name: Slack Notification on CI Pipeline Failure
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  NotifyOnFailure:
    runs-on: ubuntu-latest
    needs: CI
    if: ${{ needs.CI.outputs.ci-status == 'failure' }}
    steps:
      - name: Debug GitHub context
        run: echo '${{ toJson(github) }}'

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C07624WJDS4' # Update with your Slack channel ID
          slack-message: |
            :x: CI Pipeline failed for ${{ github.repository }} on branch ${{ github.ref_name }}
            Actor: ${{ github.event.pull_request.user.login }}
            Pull-Request: <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
