name: Check Secrets

on: [push]

jobs:
  secrets:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up git-secrets
      run: |
        git clone https://github.com/awslabs/git-secrets.git
        cd git-secrets
        sudo make install

    - name: Configure git-secrets
      run: |
        git secrets --install
        git secrets --register-aws
        git secrets --add 'API_KEY_[A-Za-z0-9]+'
        git secrets --add 'SECRET_KEY_[A-Za-z0-9]+'

    - name: Display git-secrets configuration
      run: git secrets --list

    - name: Scan for secrets
      run: |
        git secrets --scan

