name: OWASP ZAP Scan
on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull OWASP ZAP image
        run: docker pull ghcr.io/zaproxy/zaproxy:stable

      - name: Start OWASP ZAP
        run: docker run -u zap -p 8080:8080 -d --name zap ghcr.io/zaproxy/zaproxy:stable zap.sh -daemon -port 8080 -host 0.0.0.0 -config api.disablekey=true

      - name: Wait for ZAP to start
        run: sleep 30

      - name: Run ZAP baseline scan
        run: docker exec zap zap-baseline.py -t http://developmentvm1-klasb2c.westeurope.cloudapp.azure.com -r zap_report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: zap_report.html
